print('Hello World')
print('Como te llamas?')
nombre = input()
print('Un placer de conocer ' + nombre)
print('La cantidad de letras de tu nombres es: ')
print(len(nombre))
print('Cual es tu edad?')
edad = int(input())
print('Tu edad es:' + str(edad))